# ===== base build stage =====
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-base
WORKDIR /src
COPY . .
RUN dotnet restore ./MyBooks.sln

# ===== base runtime stage =====
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime-base
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
